project_id = "pjcegphrngpedujeatrl"

[functions.get-gallery-id]
verify_jwt = false

[functions.create-stripe-connect-account]
verify_jwt = false

[functions.create-stripe-account-session]
verify_jwt = false

[functions.ai-chat]
verify_jwt = false

[functions.create-gallery-checkout]
verify_jwt = false

[functions.download-gallery-zip]
verify_jwt = false

[functions.reactivate-gallery]
verify_jwt = false

[functions.confirm-gallery-reactivation]
verify_jwt = false

[functions.confirm-booking]
verify_jwt = false

