import { useState, useEffect, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { supabase } from "@/integrations/supabase/client";
import { toast } from "sonner";
import { Sparkles, Copy, RefreshCw, FileText } from "lucide-react";

interface CarrosselCaptionProps {
  tema: string;
  nicho: string;
  tom: string;
  tituloSerie: string;
  autoGenerate?: boolean;
}

const CarrosselCaption = ({ tema, nicho, tom, tituloSerie, autoGenerate }: CarrosselCaptionProps) => {
  const [caption, setCaption] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const hasAutoGenerated = useRef(false);

  useEffect(() => {
    if (autoGenerate && !hasAutoGenerated.current && !caption) {
      hasAutoGenerated.current = true;
      handleGenerate();
    }
  }, [autoGenerate]);

  const handleGenerate = async () => {
    setIsLoading(true);
    try {
      const { data, error } = await supabase.functions.invoke("generate-caption", {
        body: { tema, nicho, tom, titulo_serie: tituloSerie },
      });
      if (error) throw new Error(error.message);
      if (data?.error) throw new Error(data.error);
      setCaption(data.caption);
      toast.success("Legenda gerada!");
    } catch (err: any) {
      toast.error(err.message || "Erro ao gerar legenda");
    } finally {
      setIsLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(caption);
    toast.success("Legenda copiada!");
  };

  return (
    <div className="rounded-lg border border-border bg-card p-4 space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <FileText className="h-4 w-4 text-primary" />
          <h3 className="font-semibold text-sm text-foreground">Legenda do Post</h3>
        </div>
        <div className="flex gap-2">
          {caption && (
            <>
              <Button size="sm" variant="outline" onClick={handleCopy}>
                <Copy className="h-3 w-3 mr-1" /> Copiar
              </Button>
              <Button size="sm" variant="outline" onClick={handleGenerate} disabled={isLoading}>
                <RefreshCw className={`h-3 w-3 mr-1 ${isLoading ? "animate-spin" : ""}`} /> Regenerar
              </Button>
            </>
          )}
          {!caption && (
            <Button size="sm" onClick={handleGenerate} disabled={isLoading}>
              <Sparkles className={`h-3 w-3 mr-1 ${isLoading ? "animate-pulse" : ""}`} />
              {isLoading ? "Gerando..." : "Gerar Legenda"}
            </Button>
          )}
        </div>
      </div>
      {caption && (
        <Textarea
          value={caption}
          onChange={(e) => setCaption(e.target.value)}
          className="min-h-[150px] text-sm"
          placeholder="Legenda gerada aparecerá aqui..."
        />
      )}
    </div>
  );
};

export default CarrosselCaption;
