
ALTER TABLE public.photographer_site
  ADD COLUMN IF NOT EXISTS header_bg_color TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS header_text_color TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS header_visible_socials JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS footer_bg_color TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS footer_text_color TEXT DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS footer_show_logo BOOLEAN DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS footer_show_socials BOOLEAN DEFAULT TRUE,
  ADD COLUMN IF NOT EXISTS footer_visible_socials JSONB DEFAULT NULL,
  ADD COLUMN IF NOT EXISTS footer_preset TEXT DEFAULT 'social';
